[settings]
experimental = true
minimum_release_age = "7d"
npm.package_manager = "bun"

[tools]
bun = "1"
hk = "1.49.0"
node = "24"
pkl = "0.31"
usage = "latest"

[hooks]
enter = ["hk install --mise"]
